name: Extract VLESS

on:
workflow_dispatch:
schedule:
- cron: "*/15 * * * *"

jobs:
run:
runs-on: ubuntu-latest

permissions:
  contents: write

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - name: Install Packages
    run: |
      pip install requests beautifulsoup4

  - name: Run Script
    run: |
      python main.py

  - name: Commit Changes
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"

      git add vless.txt vless.json

      if git diff --staged --quiet; then
        echo "No changes"
      else
        git commit -m "Update VLESS configs"
        git push
      fi
